[package]
name = "axum-playground"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
axum = "0.6.7"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.2"
serde_json = "1.0.2"
jsonwebtoken = "8"
log = "0.4.14"
log4rs = '1.0.0'
diesel = { version = "1.4.8", features = ["postgres", "r2d2", "extras", "serde_json", "chrono"] }
dotenv = "0.15.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
chrono = {version = "0.4", features = ["serde"]}
thiserror = "1.0.29"