version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: axum_postgres
    environment:
      POSTGRES_USER: foo_user
      POSTGRES_PASSWORD: foo_password
      POSTGRES_DB: foo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foo_user"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 